USE DATABASE IE_DB;

-- Pré requisitos: 
    -- Ingestão via o AirByte: Source to SnowFlake
    -- Após rodar DBT

-- #Estrutura: 
    -- STATING
        SELECT 'DESCRIÇÃO', '0' FROM DUAL
        UNION ALL
        SELECT 'DISPONIBILIDADE_USINA_2025_07', COUNT(*) FROM STAGING.DISPONIBILIDADE_USINA_2025_07
        UNION ALL
        SELECT 'DISPONIBILIDADE_USINA_2025_08', COUNT(*) FROM STAGING.DISPONIBILIDADE_USINA_2025_08
        UNION ALL
        SELECT 'DISPONIBILIDADE_USINA_2025_09', COUNT(*) FROM STAGING.DISPONIBILIDADE_USINA_2025_09;    
        
    -- CORE
        SELECT * FROM CORE.DIM_USINA LIMIT 10;
        SELECT * FROM CORE.DIM_LOCALIDADE LIMIT 10;
        SELECT * FROM CORE.DIM_TEMPO LIMIT 10;
        SELECT * FROM CORE.FACT_DISPONIBILIDADE LIMIT 10;     

-- ########################################
-- DRAFT 
-- ########################################

-- Validação básica
DESCRIBE TABLE IE_DB.STAGING.DISPONIBILIDADE_USINA_2025_08;

-- DROP TABLE STAGING.K4WO2N_DISPONIBILIDADE_USINA_2025_07;
SELECT COUNT(*) FROM STAGING.DISPONIBILIDADE_USINA_2025_08;
SELECT * FROM STAGING.DISPONIBILIDADE_USINA_2025_08 LIMIT 5;

-- DROP VIEW CORE.STG_USINA_DISP; 
SELECT * FROM STAGING.STG_USINA_DISP; 

-- Outras validações 

DESCRIBE TABLE STAGING.DISPONIBILIDADE_USINA_2025_07;
DESCRIBE TABLE STAGING.DISPONIBILIDADE_USINA_2025_08;
DESCRIBE TABLE STAGING.DISPONIBILIDADE_USINA_2025_09;

-- DROP TABLE STAGING.DISPONIBILIDADE_USINA_2025_08;

SELECT 'DESCRIÇÃO', '0' FROM DUAL
UNION ALL
SELECT 'DISPONIBILIDADE_USINA_2025_07', COUNT(*) FROM STAGING.DISPONIBILIDADE_USINA_2025_07
UNION ALL
SELECT 'DISPONIBILIDADE_USINA_2025_08', COUNT(*) FROM STAGING.DISPONIBILIDADE_USINA_2025_08
UNION ALL
SELECT 'DISPONIBILIDADE_USINA_2025_09', COUNT(*) FROM STAGING.DISPONIBILIDADE_USINA_2025_09;

-- 
--- DROP VIEW STAGING.STG_USINA_DISP_2025_09; 
-- comparando os totais: 
WITH contagens_por_tabela AS (
    -- Esta é a sua consulta original, com nomes de colunas definidos
    SELECT 'DISPONIBILIDADE_USINA_2025_07' AS nome_tabela, COUNT(*) AS numero_de_linhas FROM STAGING.DISPONIBILIDADE_USINA_2025_07
    UNION ALL
    SELECT 'DISPONIBILIDADE_USINA_2025_08' AS nome_tabela, COUNT(*) AS numero_de_linhas FROM STAGING.DISPONIBILIDADE_USINA_2025_08
    UNION ALL
    SELECT 'DISPONIBILIDADE_USINA_2025_09' AS nome_tabela, COUNT(*) AS numero_de_linhas FROM STAGING.DISPONIBILIDADE_USINA_2025_09
)

SELECT
    SUM(numero_de_linhas) AS total_geral_de_linhas
FROM contagens_por_tabela;
-- 496368

SELECT COUNT(*) FROM STAGING.STG_USINA_DISP;  
-- 496368

-- Mais validações 
DESCRIBE VIEW STAGING.STG_USINA_DISP; 

SELECT * FROM STAGING.STG_USINA_DISP;

-- Use uma role de administrador para esta verificação
USE ROLE ACCOUNTADMIN;

-- O dbt cria views por padrão, então vamos procurar por uma view
SHOW VIEWS LIKE 'DIM_USINA' IN SCHEMA CORE;

SELECT * FROM CORE.DIM_USINA LIMIT 10;

-- DROP SCHEMA IF EXISTS STAGING_CORE CASCADE;
-- DROP SCHEMA IF EXISTS CORE_STAGING CASCADE;


SELECT * FROM CORE.DIM_USINA LIMIT 10;
SELECT * FROM CORE.DIM_LOCALIDADE LIMIT 10;
SELECT * FROM CORE.DIM_TEMPO LIMIT 10;